name: Daily Cypress Test for YouTube
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Instalar dependências
        run: npm ci

      - name: Executar teste funcional Cypress
        run: npm run test

      - name: Enviar resultado para o Google Chat
        uses: google-github-actions/chat@v1.1.0
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          message: |
            Teste Funcional Cypress concluído:
            - Resultado: ${{ job.status }}
            - Commit: ${{ github.sha }}
            - Autor: ${{ github.actor }}
            - URL do Action: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
